import { triakisTetrahedron } from './catalan/triakisTetrahedron.mjs';
import { rhombicDodecahedron } from './catalan/rhombicDodecahedron.mjs';
import { tetrakisHexahedron } from './catalan/tetrakisHexahedron.mjs';
import { triakisOctahedron } from './catalan/triakisOctahedron.mjs';
import { deltoidalIcositetrahedron } from './catalan/deltoidalIcositetrahedron.mjs';
import { pentagonalIcositetrahedronDextro } from './catalan/pentagonalIcositetrahedronDextro.mjs';
import { pentagonalIcositetrahedronLaevo } from './catalan/pentagonalIcositetrahedronLaevo.mjs';
import { rhombicTriacontahedron } from './catalan/rhombicTriacontahedron.mjs';
import { disdyakisDodecahedron } from './catalan/disdyakisDodecahedron.mjs';
import { pentakisDodecahedron } from './catalan/pentakisDodecahedron.mjs';
import { triakisIcosahedron } from './catalan/triakisIcosahedron.mjs';
import { deltoidalHexecontahedron } from './catalan/deltoidalHexecontahedron.mjs';
import { pentagonalHexecontahedronDextro } from './catalan/pentagonalHexecontahedronDextro.mjs';
import { pentagonalHexecontahedronLaevo } from './catalan/pentagonalHexecontahedronLaevo.mjs';
import { disdyakisTriacontahedron } from './catalan/disdyakisTriacontahedron.mjs';

let catalan = {};
catalan['triakisTetrahedron'] = triakisTetrahedron;
catalan['rhombicDodecahedron'] = rhombicDodecahedron;
catalan['tetrakisHexahedron'] = tetrakisHexahedron;
catalan['triakisOctahedron'] = triakisOctahedron;
catalan['deltoidalIcositetrahedron'] = deltoidalIcositetrahedron;
catalan['pentagonalIcositetrahedronDextro'] = pentagonalIcositetrahedronDextro;
catalan['pentagonalIcositetrahedronLaevo'] = pentagonalIcositetrahedronLaevo;
catalan['rhombicTriacontahedron'] = rhombicTriacontahedron;
catalan['disdyakisDodecahedron'] = disdyakisDodecahedron;
catalan['pentakisDodecahedron'] = pentakisDodecahedron;
catalan['triakisIcosahedron'] = triakisIcosahedron;
catalan['deltoidalHexecontahedron'] = deltoidalHexecontahedron;
catalan['pentagonalHexecontahedronDextro'] = pentagonalHexecontahedronDextro;
catalan['pentagonalHexecontahedronLaevo'] = pentagonalHexecontahedronLaevo;
catalan['disdyakisTriacontahedron'] = disdyakisTriacontahedron;

export { catalan };
